abstract final class AssetsManger{
  static const String splash = "assets/images/Splash Screen.png";
  static const String ahadeth = "assets/images/ahadeth.svg";
  static const String ahasethback = "assets/images/ahadeth_Background.png";
  static const String leftcorner = "assets/images/left_corner.png";
  static const String logo = "assets/images/Logo.png";
  static const String mosque = "assets/images/mosque.png";
  static const String mosque2 = "assets/images/mosque2.png";
  static const String quran = "assets/images/quran.svg";
  static const String quranback = "assets/images/quran_Background.png";
  static const String qurancard = "assets/images/quran_card.png";
  static const String radio = "assets/images/radio.svg";
  static const String radioback = "assets/images/radio_back.png";
  static const String rightcorner = "assets/images/right_corner.png";
  static const String sebha = "assets/images/sebha.svg";
  static const String sebhaback = "assets/images/sebha_Background.png";
  static const String suranumber = "assets/images/sura_number.svg";
  static const String time = "assets/images/time.svg";
  static const String timeback = "assets/images/time_Background.png";
  static const String SebhaBody = "assets/images/SebhaBody.png";
  static const String sebhahead = "assets/images/sebhahead.png";
  static const String intro1 = "assets/images/intro1.png";
  static const String intro2 = "assets/images/intro2.png";
  static const String intro3 = "assets/images/intro3.png";
  static const String intro4 = "assets/images/intro4.png";
  static const String intro5 = "assets/images/intro5.png";
  static const String soundWave = "assets/images/soundWave.png";
  static const String Hadithtxtback = "assets/images/Hadithtxtback.png";
}